"use client";

import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { Send, X, Loader2 } from "lucide-react";
import { cn } from "@/lib/cn";
import { poseWebp } from "@/lib/mascot/manifest";

interface Msg {
  role: "tiru" | "user";
  text: string;
}

const GREETING: Msg = {
  role: "tiru",
  text:
    "Hi, I'm Tiru! Tell me what's confusing, suggest how to make your lessons better, " +
    "or just ask me anything. Your feedback shapes what you learn next.",
};

/**
 * Global floating "chat with Tiru" button. Gives the learner one place to send
 * feedback (which is stored to improve lessons) and to interact with Tiru. The
 * replies are generated by Claude via /api/tiru (Claude subscription).
 */
export function TiruChat() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);
  const [msgs, setMsgs] = useState<Msg[]>([GREETING]);
  const [input, setInput] = useState("");
  const [busy, setBusy] = useState(false);
  const listRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    listRef.current?.scrollTo({ top: listRef.current.scrollHeight, behavior: "smooth" });
  }, [msgs, busy, open]);

  useEffect(() => {
    if (open) inputRef.current?.focus();
  }, [open]);

  const send = async () => {
    const text = input.trim();
    if (!text || busy) return;
    const history = msgs.slice(-6).map((m) => ({ role: m.role, text: m.text }));
    setMsgs((m) => [...m, { role: "user", text }]);
    setInput("");
    setBusy(true);
    try {
      const res = await fetch("/api/tiru", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: text, history, page: pathname }),
      });
      const data = await res.json().catch(() => ({}));
      setMsgs((m) => [...m, { role: "tiru", text: data.reply || "Thanks — I've noted that!" }]);
    } catch {
      setMsgs((m) => [
        ...m,
        { role: "tiru", text: "I couldn't reach my brain just now, but I saved your note. Try again in a moment?" },
      ]);
    } finally {
      setBusy(false);
    }
  };

  return (
    <>
      {/* Chat panel */}
      {open && (
        <div
          className={cn(
            "fixed bottom-40 right-4 z-[60] flex h-[min(560px,72vh)] w-[min(380px,calc(100vw-2rem))]",
            "flex-col overflow-hidden rounded-3xl border-2 border-border bg-surface shadow-2xl animate-rise",
            "md:bottom-24 md:right-6"
          )}
          role="dialog"
          aria-label="Chat with Tiru"
        >
          {/* Header */}
          <div className="flex items-center gap-3 border-b border-border bg-primary px-4 py-3">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={poseWebp("happy")} alt="Tiru" width={36} height={36} className="h-9 w-9 shrink-0 object-contain" />
            <div className="min-w-0 flex-1">
              <p className="font-display text-sm font-bold text-primary-fg">Chat with Tiru</p>
              <p className="truncate text-xs text-primary-fg/80">Your feedback makes lessons better</p>
            </div>
            <button
              onClick={() => setOpen(false)}
              aria-label="Close chat"
              className="grid h-8 w-8 shrink-0 place-items-center rounded-full text-primary-fg/90 transition-colors hover:bg-black/10"
            >
              <X className="h-5 w-5" />
            </button>
          </div>

          {/* Messages */}
          <div ref={listRef} className="flex-1 space-y-3 overflow-y-auto scroll-thin p-4">
            {msgs.map((m, i) => (
              <div key={i} className={cn("flex", m.role === "user" ? "justify-end" : "justify-start")}>
                <div
                  className={cn(
                    "max-w-[82%] rounded-2xl px-3.5 py-2.5 text-sm leading-relaxed",
                    m.role === "user"
                      ? "rounded-br-sm bg-primary text-primary-fg"
                      : "rounded-bl-sm bg-surface-alt text-text"
                  )}
                >
                  {m.text}
                </div>
              </div>
            ))}
            {busy && (
              <div className="flex justify-start">
                <div className="inline-flex items-center gap-2 rounded-2xl rounded-bl-sm bg-surface-alt px-3.5 py-2.5 text-sm text-muted">
                  <Loader2 className="h-4 w-4 animate-spin" /> Tiru is thinking…
                </div>
              </div>
            )}
          </div>

          {/* Input */}
          <div className="flex items-end gap-2 border-t border-border p-3">
            <textarea
              ref={inputRef}
              value={input}
              onChange={(e) => setInput(e.target.value)}
              onKeyDown={(e) => {
                if (e.key === "Enter" && !e.shiftKey) {
                  e.preventDefault();
                  send();
                }
              }}
              rows={1}
              placeholder="Share feedback or ask Tiru…"
              className="max-h-28 min-h-[42px] flex-1 resize-none rounded-2xl border-2 border-border bg-surface px-3.5 py-2.5 text-sm text-text outline-none transition-colors focus:border-primary"
            />
            <button
              onClick={send}
              disabled={busy || !input.trim()}
              aria-label="Send"
              className="grid h-[42px] w-[42px] shrink-0 place-items-center rounded-2xl bg-primary text-primary-fg transition-all hover:brightness-105 active:scale-95 disabled:opacity-40"
            >
              <Send className="h-5 w-5" />
            </button>
          </div>
        </div>
      )}

      {/* Floating Tiru button */}
      <button
        onClick={() => setOpen((o) => !o)}
        aria-label={open ? "Close Tiru chat" : "Give feedback or chat with Tiru"}
        className={cn(
          "fixed bottom-20 right-4 z-[60] grid h-16 w-16 place-items-center rounded-full border-2 border-primary-fg/20",
          "bg-primary shadow-xl transition-transform hover:scale-105 active:scale-95 md:bottom-6 md:right-6"
        )}
      >
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={poseWebp(open ? "idle" : "wave")}
          alt="Tiru"
          width={48}
          height={48}
          className="h-12 w-12 object-contain drag-none"
        />
        {!open && (
          <span className="absolute right-1 top-1 h-3 w-3 rounded-full border-2 border-primary bg-secondary" />
        )}
      </button>
    </>
  );
}
