// On-demand lesson generation (app-side). Mirrors the worker's runGenerateLesson
// but runs inside the Next.js API so bookmark/prerequisite lessons work without a
// running worker. Deterministic shaping (question cleanup, declared prerequisites)
// stays in code; only the prose/MCQ authoring uses the LLM. Returns null when no
// LLM is configured (caller falls back to a static lesson).

import { getRedis } from "@/lib/redis";
import { getLLM, parseJsonFromText } from "@/lib/core/llm";
import { getArticle } from "@/lib/articles";
import { identifyConcept, prerequisiteChain, conceptLabel } from "./plan";

export interface GenMCQ {
  id: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string;
  citation: string;
}

export interface GenLesson {
  id: string;
  title: string;
  topic: string;
  concept: string;
  questions: GenMCQ[];
  generated: true;
  createdAt: number;
  articleId?: string;
  /** Concepts this lesson assumes the learner already knows (deterministic). */
  prereqs?: string[];
}

const lessonKey = (id: string) => `lesson:gen:${id}`;
const ORDINALS = ["first", "second", "third", "fourth", "fifth"];

function prompt(topic: string, grounding: string, index: number, count: number): string {
  const focus =
    count > 1
      ? `This is lesson ${index} of ${count}. Focus on the ${ORDINALS[index - 1] ?? `${index}th`} portion of the material so the set of lessons covers the whole article without repeating.`
      : "";
  return `You are Tiruno's lesson author. Write a short, accurate micro-lesson on "${topic}" for a learner. ${focus}

Ground every claim in this source material. Do not invent facts beyond it; where it's thin, rely on well-established fundamentals of the topic:
---
${grounding.slice(0, 6000) || "(no extra material retrieved; use well-established fundamentals)"}
---

Respond with ONLY one JSON object (no prose, no code fences) of exactly this shape:
{"title":"...","concept":"a 3-5 sentence plain-language explanation a tutor would say aloud","questions":[{"prompt":"...","options":["..","..","..",".."],"answer":0,"explanation":"one sentence on why the correct option is right","citation":"short source label"}]}

Include exactly 5 questions. Each question must have exactly 4 options and "answer" as the 0-based index of the correct option. Keep it tight and demo-sized.`;
}

/**
 * Return a cached generated lesson, or author one now from a topic/article.
 * `index`/`count` let multi-lesson articles cover different portions.
 */
export async function getOrGenerateLesson(opts: {
  id: string;
  topic?: string;
  articleId?: string;
  index?: number;
  count?: number;
}): Promise<GenLesson | null> {
  const r = getRedis();

  // Cached (e.g. authored earlier by the worker or a previous request).
  try {
    const raw = await r.get(lessonKey(opts.id));
    if (raw) return JSON.parse(raw) as GenLesson;
  } catch {
    /* fall through to generate */
  }

  const llm = getLLM();
  if (!llm) return null; // no key → caller falls back to a static lesson

  let grounding = "";
  let topic = (opts.topic || "").trim();
  if (opts.articleId) {
    const a = await getArticle(opts.articleId);
    if (a) {
      grounding = [a.title, a.summary, a.text].filter(Boolean).join("\n\n");
      topic = topic || a.topic || a.title;
    }
  }
  if (!topic) topic = "this topic";

  // Deterministic: what does this lesson assume the learner already knows?
  const concept = identifyConcept(`${topic}. ${grounding}`);
  const prereqs = concept ? prerequisiteChain(concept).map(conceptLabel) : [];

  let text = "";
  try {
    text = await llm.complete(prompt(topic, grounding, opts.index ?? 1, opts.count ?? 1), {
      system: "You output only valid JSON. Be concise and grounded in the data provided.",
      maxTokens: 1200,
      temperature: 0.5,
      json: true,
    });
  } catch {
    return null;
  }

  const parsed = parseJsonFromText<{ title?: string; concept?: string; questions?: GenMCQ[] }>(text, {});
  const questions: GenMCQ[] = (parsed.questions ?? [])
    .filter((q) => q && q.prompt && Array.isArray(q.options) && q.options.length >= 2)
    .slice(0, 5)
    .map((q, i) => ({
      id: `q${i + 1}`,
      prompt: String(q.prompt),
      options: q.options.slice(0, 4).map((o) => String(o)),
      answer: Math.max(0, Math.min((q.options.length || 1) - 1, Number(q.answer) || 0)),
      explanation: String(q.explanation ?? ""),
      citation: String(q.citation ?? "Generated by Tiru"),
    }));

  if (!questions.length) return null;

  const lesson: GenLesson = {
    id: opts.id,
    title: String(parsed.title || `A lesson on ${topic}`),
    topic,
    concept: String(parsed.concept || ""),
    questions,
    generated: true,
    createdAt: Date.now(),
    ...(opts.articleId ? { articleId: opts.articleId } : {}),
    ...(prereqs.length ? { prereqs } : {}),
  };

  try {
    await r.set(lessonKey(opts.id), JSON.stringify(lesson), "EX", 60 * 60 * 24 * 7);
  } catch {
    /* best effort */
  }
  return lesson;
}
